### ISSUE TITLE
Error with Database Structure

### ISSUE THREAD

**Issue by fredbird1012** [JudgeZarbi/smb2-team-transfer-tool#68]
I am using the latest version of smb2-team-transfer-tool (v0.3.3).  I have tried to import several teampacks and keep getting the following error:

Traceback (most recent call last):
  File "main.py", line 60, in <module>
    else:
  File "main.py", line 28, in main
    success = False
  File "imports\team.py", line 150, in import_team
  File "imports\team.py", line 63, in _write_data_to_db
sqlite3.OperationalError: no such table: t_baseball_player_colors
This should be reported as a bug.
Press Enter to exit.

Not sure what is causing the problem.  I have Python 2.7 and 3.6 installed to my computer.

![smb2 team transfer tool error](https://user-images.githubusercontent.com/29557106/41672305-93d32fce-7487-11e8-9d29-233b0f2e557f.png)

![smb2 team transfer tool directory](https://user-images.githubusercontent.com/29557106/41672373-c4ec46ea-7487-11e8-9c71-01a9a6fe717d.png)

**Comment by JudgeZarbi** [comment]
I've seen this one before a few times. It's to do with the save data still being on the first version. Make sure the game is up to date, and then you can either modify something in the customisation menu to trigger the "Would you like to save" menu to appear, or I believe starting a game works for that as well.

I appreciate the error message for that isn't helpful at all, I've got an improved error message coming in the next version.

Also, Python is included within the executable yourself, so you don't have to worry about installing it yourself. :)

**Comment by fredbird1012** [comment]
Thanks for the quick reply.  I tried modifying teams and players in the customization menu and saving along with deleting my old season and creating a new one.  For some reason I am still getting the error message with the tool.  I thought I was on the most recent version of the game.  I will check for updates to the game to make sure I have them all.  What is the most current version of the game I should be on?  Thanks again for your help.

**Comment by JudgeZarbi** [comment]
Update 3 is the most recent update, which the tool should definitely work with. If it still doesn't work, would you mind uploading your save file here for me? (You can find it by pasting `%USERPROFILE%\AppData\Local\Metalhead\Super Mega Baseball 2\` into Windows Exporer)

**Comment by fredbird1012** [comment]
I was missing Update 3.  I installed Update 3 and the tool is now working.  All the teams I have added are now showing in the game.  Great tool!  Thanks again for all your help.

**Comment by JudgeZarbi** [comment]
Awesome news. I'm glad to hear you got it all working!
